apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-static
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: "" # empty because we Are doing static provisioning
  volumeName: "efs-static"
  resources:
    requests:
      storage: 5Gi