kind: Pod
apiVersion: v1
metadata:
  name: env
spec:
  containers:
  - name: niginx
    image: niginx
    env:
    - name: course
      value: DevOps
    - name: trainer
      value: "siva reddy"
    - name: duration
      value: "120hrs"