kind: Service
apiVersion: v1
metadata:
  name: nginx-np
spec:
  type: NodePort
  selector:   #lables are used as selectors
    project: expense
    environment: dev
    component: backend
    version: "1.0.0"
    demo: np
  ports:
  - protocol: TCP
    port: 80  #service port
    targetPort: 80

---
kind: Pod
apiVersion: v1
metadata:
 name: backend-np 
 labels:
    project: expense
    component: backend
    environment: dev
    version: "1.0.0"
    demo: np 
spec:
  containers:
  - name: k8nginx
    image: nginx
    