apiVersion: v1
kind: Pod
metadata:
    name: sa-demo
    namespace: expense
spec:
  # one pod can contain multiple containers
  serviceAccount: aws-expense-mysql-secret
  
  containers: 
    - name: k8nginx 
      image: nginx
