apiVersion: v1
kind: Pod
metadata:
    name: sa-demo
    namespace: expense
spec:
  # one pod can contain multiple containers
  serviceAccount: aws-expense-mysql-secret
  initContainers:
  - name: awscli
    image: amazon/aws-cli
    command: [ 'sh', '-c', 'aws secretsmanager get-secret-value --secret-id expense/mysql/creds --query SecretString --output text > /secrets/.env ']
    volumeMounts:
    - mountpath: /secrets
      name: secret-volume
  containers: 
  - name: k8nginx 
    image: nginx
    volumeMounts:
    - mountpath: /secrets
      name: secret-volume
  volumes:
  - name: secret-volume
    emptyDir: {}